explore-siargao/explore-siargao

apps/web/module/LandingPage/components/Header.tsx

Fixed padding
To make presentable

fix: Fixed the padding of content in header

---

apps/api/src/routes/listing/index.ts
apps/api/src/routes/listing/service/wishGroup.ts

New api routes
For adding notes in wish list

feat(api): Created new endpoint for adding notes in wish list group

---

apps/web/common/components/WishlistBoxContainer.tsx
apps/web/common/components/WishlistsItemContainer.tsx
apps/web/module/AccountSettings/Wishlist.tsx
apps/web/module/AccountSettings/components/modals/AddNoteModal.tsx

Fix bug
To display the correct image in wish group

Fix:Wish group image display

---

apps/api/src/prisma/migrations/20240126021003_created_taxes/migration.sql
apps/api/src/prisma/schema.prisma
package-lock.json

Created taxes schema model
\_Provide a reason for the pull request
for checking and merging the changes
to update schema model
\_Why is the change needed. It is a feature, story, bugfix or hotfix?
It is a task
https://linear.app/explore-siargao/issue/ENG-255/taxes-schema-model

[Task-Story] Created taxes Schema model

---

apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/default.ts

Added new endpoint
Will use to deactivate user account

Deactivate account api endpoint

---

apps/api/src/routes/users/index.ts
apps/web/module/AccountSettings/hooks/useDeactivateAccount.ts

Added custom hook for deactivating account
To connect to backend of user deactivate

[Task-Story] Deactivate account hook

---

apps/web/app/gift/page.tsx
apps/web/common/types/global.ts
apps/web/module/Bookings/hooks/useAddTax.ts
package-lock.json
packages/constants/src/index.ts

https://linear.app/explore-siargao/issue/ENG-262/add-tax-hook
\_Provide a reason for the pull request
Created a custom hook (useAddTax) and requested a pull request.
\_Why is the change needed. It is a feature, story, bugfix or hotfix?
To add my code addTask, it is a story.

[Task-Story] add tax hook

---

apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/default.ts

Added new api endpoint 
will use to update user password

[Task-Story] Change password api endpoint

---

apps/web/module/AccountSettings/hooks/useUpdateAccountPassword.ts

Added custom hook for change password
To connect to change password backend

[Task-Story] Change password hook

---

apps/api/src/prisma/migrations/20240126063322_add_country_to_personal_info/migration.sql
apps/api/src/prisma/schema.prisma
apps/api/src/routes/users/service/auth.ts
packages/contract/src/User/zod.ts

Added colum country in personal info table
To manipulate the currency
https://linear.app/explore-siargao/issue/ENG-277/add-new-column-on-personalinfo-table-name-country

[Task-Story] Added new column on PersonalInfo table name country

---

apps/web/module/Bookings/hooks/useGetTaxByUser.ts

https://linear.app/explore-siargao/issue/ENG-263/get-tax-by-user-id-hook
\_Provide a reason for the pull request
PR for adding custom hook useGetTaxByUser
\_Why is the change needed. It is a feature, story, bugfix or hotfix?
finished task-story get tax by user id hook. 

[Task-Story] get tax by user id hook

---

apps/web/module/AccountSettings/hooks/useUpdateCurrency.ts

Added custom hook useUpdateCurrency
For Testing. It is a task story
https://linear.app/explore-siargao/issue/ENG-273/update-currency-hook

[Task-Story] Update currency hook

---

apps/web/module/AccountSettings/hooks/useUpdateLanguage.ts

added custom hook useUpdateLanguage.
to check the code and test functionality
For checking and merging.
This is a task-story
https://linear.app/explore-siargao/issue/ENG-275/update-language-hook

[Task-Story] Update language hook

---

apps/api/src/prisma/migrations/20240126070002_added_language_to_personal_info/migration.sql
apps/api/src/prisma/schema.prisma
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/auth.ts
apps/api/src/routes/users/service/default.ts
apps/api/src/routes/users/service/personalInfo.ts
package-lock.json

Added api endpoint for update language
To make the language updatable
https://linear.app/explore-siargao/issue/ENG-274/update-language-api-endpoint

[Task-Story] Update language api endpoint

---

README.md
docs/local_database_setup.md

Added documentation for setting up local database
To improve local development
https://linear.app/explore-siargao/issue/ENG-278/setup-local-database

[Task-Story] Added documentation for setting up local database

---

apps/api/src/prisma/migrations/20240126084629_currency_column/migration.sql
apps/api/src/prisma/schema.prisma
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/auth.ts
apps/api/src/routes/users/service/default.ts
apps/api/src/routes/users/service/personalInfo.ts

Added new api endpoint for updating currency
To make the update currency work
https://linear.app/explore-siargao/issue/ENG-272/update-currency-api-endpoint

[Task-Story] Update currency api endpoint

---

apps/api/src/prisma/migrations/20240129020608_npx_prisma_generate/migration.sql
apps/api/src/prisma/schema.prisma

Modified review schema 
Added categoryRates
https://linear.app/explore-siargao/issue/ENG-267/add-database-model-for-reviews

[Task-Story] Added database model for Reviews

---

apps/web/module/Bookings/hooks/useGetReviewsByUserId.ts
package-lock.json
package.json

Added custom hook useGetReviewsByUserID
For merging and testing of functionality

[Task-Story] Get reviews by userId

---

apps/api/src/prisma/schema.prisma

Edited addresses schema
This is a task-story, to update and merge necessary files and codes specifically in addresses schema.

[Task-Story] Edited addresses schema

---

apps/api/src/routes/listing/service/reviews.ts
packages/contract/src/BackendResponse/zod.ts

Modified api routes for get reviews by listing
To Include data reviews per category

[Task-Story] Get all reviews by listing id endpoint

---

apps/web/common/helpers/formatCurrency.ts

A reusable function for formatting amounts of money.

[Task-Story] Add comma to money amounts

---

apps/web/common/components/ui/Asterisk.tsx
apps/web/common/components/ui/Input.tsx
apps/web/module/AccountSettings/components/Address.tsx
apps/web/module/AccountSettings/components/EmailAddress.tsx
apps/web/module/AccountSettings/components/EmergencyContact.tsx
apps/web/module/AccountSettings/components/LegalName.tsx
apps/web/module/AccountSettings/components/Payments.tsx
apps/web/module/AccountSettings/components/PhoneNumber.tsx
apps/web/module/AccountSettings/components/modals/AddCardDetailModal.tsx
apps/web/module/AccountSettings/components/modals/AddWishlistModal.tsx
apps/web/module/AccountSettings/components/modals/MenuModal.tsx
apps/web/module/Authentication/ForgotPassword/index.tsx
apps/web/module/Authentication/NewPassword/index.tsx
apps/web/module/Authentication/components/LoginForm.tsx
apps/web/module/Authentication/components/PreSignUpForm.tsx
apps/web/module/Authentication/components/SignUpForm.tsx
apps/web/module/gift/index.tsx

Fix input attributes id and label

[Task-Story] Added reusable asterisk component for required input

---

apps/api/src/prisma/migrations/20240131023932_/migration.sql
apps/api/src/routes/listing/service/houseRules.ts
apps/api/src/routes/listing/service/rules.ts

Modified process of adding and getting house rules
Need to get correct data shape of house rules

[Bugfix-Story] Corrected the process of adding and getting house rules

---

apps/web/app/account-settings/page.tsx
apps/web/app/account-settings/wishlist/page.tsx

…nds incorrect
Correction of alignment of footer in some pages
To make a proper alignment

[bugFix-Story] Footer alignment in some pages

---

apps/web/app/account-settings/taxes/page.tsx
apps/web/app/gift/page.tsx
apps/web/common/constants/links.ts
apps/web/common/types/global.ts
apps/web/module/AccountSettings/Taxes/TaxDocuments.tsx
apps/web/module/AccountSettings/Taxes/Taxpayers.tsx
apps/web/module/AccountSettings/Taxes/index.tsx
apps/web/module/AccountSettings/index.tsx
apps/web/package.json
package-lock.json

Added country field in VAT form

[Task-Story] Add country field in VAT form

---

apps/web/module/Bookings/SingleView/components/IconDescription.tsx
apps/web/module/Bookings/SingleView/components/PlaceOffers.tsx
apps/web/module/Bookings/index.tsx
apps/web/package.json
package-lock.json

Combine the Section UI and Icon Description.
This is a task-story, to check and merge necessary changes and additionals on files and codes specifically in combining the Section UI and Icon Description.

[Task-Story] Combine the Section UI and Icon Description

---

apps/web/common/components/ui/Title.tsx
apps/web/module/Authentication/Login/index.tsx
apps/web/module/Bookings/SingleView/components/IconDescription.tsx
apps/web/module/Bookings/SingleView/components/PlaceOffers.tsx
apps/web/module/Bookings/SingleView/components/TitleSection.tsx
apps/web/module/Bookings/components/modals/PlaceOfferModal.tsx
apps/web/module/Bookings/index.tsx
apps/web/package.json
package-lock.json

These change was already reviewed on task to story level

[Story-Feature] Place offer to Booking

---

.github/workflows/prettier-format.yml
apps/web/module/AccountSettings/PersonalInfo.tsx

Fix personalInfo province to stateProvince

[Task-Story] Remove main and dev branch for prettier format

---

apps/api/src/prisma/migrations/20240202000828_added_changepassword_at/migration.sql
apps/api/src/prisma/schema.prisma
apps/api/src/routes/users/service/default.ts
apps/web/common/constants/links.ts
apps/web/module/AccountSettings/components/modals/DeactivateUserModal.tsx
apps/web/module/AccountSettings/index.tsx
packages/contract/src/User/zod.ts

Added changePasswordAt in user table
To make user that the date when user changed password is recorded

[Task-Story] Added changePasswordAt User table and update it when password is changed

---

apps/web/module/Bookings/SingleView/components/BookingDescription.tsx

Added booking description Component.
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the highlights and description.

[Task-Story] Added booking description Component

---

apps/web/module/AccountSettings/LoginSecurity/UpdatePassword.tsx

Corrected label and type in change password
To display correct inputs

[Task-Story] Changed input label for change password and its input type to password

---

apps/web/module/Bookings/hooks/useAddListingDescription.ts
apps/web/module/Bookings/hooks/useGetListingDescriptionById.ts
apps/web/module/Bookings/hooks/useGetListingDescriptionByListingId.ts
apps/web/module/Bookings/hooks/useRemoveListingDescription.ts
apps/web/module/Bookings/hooks/useUpdateListingDescription.ts

Added Listing Description hooks
This is a Story Task. To merge and check code functionality

[Task-Story] Listing Description hooks

---

apps/web/common/components/ui/Toggle.tsx
apps/web/module/Bookings/index.tsx

Added reusable Toggle on comoon/components/ui
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in notification.

[Task-Story] Added reusable Toggle on comoon/components/ui

---

apps/api/src/routes/users/service/auth.ts
apps/web/app/bookings/page.tsx
apps/web/common/components/Footer/index.tsx
apps/web/module/Authentication/components/SignUpForm.tsx
apps/web/module/Authentication/modal/OptMessageModal.tsx
apps/web/module/LandingPage/index.tsx
packages/contract/src/User/zod.ts

All commits here was reviewed on task to story level

[Story-Feature] Random changes and improvements to Bookings

---

apps/api/src/routes/listing/index.ts
apps/api/src/routes/listing/service/reviews.ts

Endpoint for getting reviews by user id
Task, the endpoint is needed for booking reviews page

[Task-Story] Add endpoint for get reviews by user id

---

apps/web/module/AccountSettings/components/modals/AddCardDetailModal.tsx

Change add payment method country select input same as on Register page
To make it Uniformed

[Task-Story] Changed add payment method country select input same as on Register page

---

apps/api/src/prisma/schema.prisma

Added new prisma model ReservationListing
Will use for reservation listing

[Task-Story] Reservation Listing Model

---

apps/web/common/components/RightRadioList.tsx
apps/web/module/Bookings/jsons/RadioList.json

Added RightRadioList reusable component
For reusable components

[Task-Story] Created reusable Right Radio List

---

apps/web/common/components/ModalContainer/index.tsx

Added ModalContainer sizes dynamically
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the modal container.

[Task-Story] Added ModalContainer sizes dynamically

---

apps/web/module/LandingPage/components/Header.tsx

Merged login and sign up button
To merge two buttons, login and sign up. It is a story.

[Task-Story] Merged login and sign up button

---

apps/api/src/routes/users/service/auth.ts

Changed notification  message when toggled settings
To display correct message from the notification when toggled settings. It is a story

[Task-Story] Changed notification  message when toggled settings

---

apps/web/module/Bookings/SingleView/components/CheckoutProcess.tsx

Added UI for first checkout process
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the  UI for first checkout process.

[Task-Story] Added UI for first checkout process

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listing/service/reportListings.ts
packages/contract/src/ReportListing/zod.ts

Adjust Report Listing Model and routes
To follow the correct data shapes

[Task - Story] Modified Report Listing Model

---

apps/web/module/Bookings/Jsons/sectionInfo.json
apps/web/module/Bookings/SingleView/components/SectionInfo.tsx
apps/web/module/Bookings/index.tsx

Added Section Info
To check design and change necessary modifications if needed. It is a story

[Task-Story] Added Section Info

---

apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/hostDetails.ts

Added endpoint for getting host-details in listing
To get specific data needed in host information in listing

[Task - Story]  Added Get hostDetails in listing api endpoint

---

apps/web/module/Bookings/hooks/useGetHostDetailsInListing.ts

What?
Added custom hook useGetHostDetailsInListing
Why?
To check code functionality and change necessary adjustments. It is story.
Hook name:  useGetHostDetailsInListing

[Task-Story] Added custom hook useGetHostDetailsInListing

---

apps/web/module/Bookings/SingleView/Review/HeadReview.tsx
apps/web/module/Bookings/SingleView/Review/OverallRating.tsx
apps/web/module/Bookings/SingleView/Review/ReviewCategory.tsx

Added UI components for booking review head
To add review head setup. It is a story.

[Task-Story] Review Head Setup

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listing/service/listing.ts
apps/api/src/routes/listing/service/wishGroup.ts
apps/web/common/components/BookingBoxContainer.tsx
apps/web/common/components/WishlistsItemContainer.tsx
apps/web/module/AccountSettings/Wishlist.tsx
apps/web/module/AccountSettings/components/modals/AddWishlistModal.tsx
apps/web/module/Bookings/index.tsx

Change ImageUrls columns to imageKeys in Listing Table
Adjusted all api routes that connected to imageKeys
Fixed error on frontend after adjustment of backend
To follow the correct pattern

[Task-Story] Adjusted listing api  and database Listing Table

---

apps/web/module/Bookings/SingleView/components/ImageGallery.tsx

Added image gallery component.
To add image gallery. It is a story.

[Task-Story] Setup Image Gallery

---

apps/web/module/Bookings/SingleView/components/ContactHost.tsx
apps/web/module/Bookings/index.tsx

Added ContactHost UI Component
To use for contacting host

[Task-Story] Contact host page ui

---

apps/web/module/Bookings/SingleView/Review/ReviewCategory.tsx
apps/web/module/Bookings/SingleView/Review/UserReview.tsx
apps/web/module/Bookings/SingleView/Review/UserReviewModal.tsx

Added user review modal.
For adding user review in modal version. It is a story.

[Task-Story] Create a modal version of Review header and User review

---

apps/web/module/AddReview/index.tsx

Added back button to actual review page
To add way to back to main page of review settings

[Task-Story] Added back button on actual reviewing page beside title

---

apps/web/module/Bookings/SingleView/components/modals/ImageGalleryModal.tsx

Added image gallery modal setup.
For adding image gallery modal setup . It is a story.

[Task-Story] Setup image gallery modal

---

apps/web/module/Bookings/SingleView/components/modals/CheckoutBreakdownModal.tsx
apps/web/module/Bookings/SingleView/components/modals/CheckoutMoreInfoModal.tsx

Added modals for showing checkout more info.
For adding modals that shows checkout more info. It is a story

[Task-Story] Modal for showing Checkout more info

---

apps/web/common/components/SpecificMap.tsx

Added setup reusable map component for a specific location.
For setting up map specific location. It is a story.

[Task-Story] Setup reusable map component for a specific location

---

apps/web/module/Bookings/SingleView/components/ThingsToKnow.tsx
apps/web/module/Bookings/SingleView/index.tsx

Added Things to know section
Will display in single view of booking

[Task-Story] Created Things to know section

---

apps/web/module/Bookings/SingleView/components/Map.tsx

Combined reusable map to Section UI
To setup map in where you'll be. It is a story.

[Task-Story] Combined reusable map to Section UI

---

apps/web/module/Bookings/SingleView/index.tsx

Added Host Information to accomodation
To complete the accomodation UI

[Task - Story] Created Host information section

---

apps/web/common/components/SpecificMap.tsx
apps/web/module/Bookings/SingleView/components/WhereYouWillBeModal.tsx

Added where you will be full width modal and changed specific map color
To setup where you'll be modal. It is a story.

[Task-Story] Put "Where you'll be" in a modal and add a map

---

apps/web/common/components/RightRadioList.tsx
apps/web/module/Bookings/SingleView/components/modals/ModalReporting.tsx

Added modal for reporting
To display list of reporting. Check code and functionality. It is a story

[Task-Story] Added modal for reporting

---

apps/web/module/Bookings/SingleView/components/ImageGallery.tsx
apps/web/module/Bookings/SingleView/components/modals/ImageGalleryModal.tsx
apps/web/module/Bookings/SingleView/index.tsx

Added Image gallery Section to accomodation
To Complete booking single page

[Task - Story] Created Title, info and Image Gallery Section

---

apps/web/module/AccountSettings/components/ReviewStarRating.tsx
apps/web/module/AddReview/hooks/useAddReview.ts

Added general rating stars accept decimals
This is a task-story, to check and merge necessary changes and additions on files and codes specifically the general rating stars that accept decimals.

[Task-Story] Added general rating stars accept decimals

---

apps/web/module/Bookings/SingleView/components/modals/ModalReporting.tsx
apps/web/module/Bookings/SingleView/components/modals/checkInOutCalendarModal.tsx
apps/web/module/Bookings/SingleView/index.tsx

Incorporated Report Listing 
To show Report Modal when "Report this listing" button was clicked.

[Task-Story] Incorporate Report Listing

---

apps/web/module/Bookings/SingleView/components/ThingsToKnow/index.tsx
apps/web/module/Bookings/SingleView/components/modals/CancellationPolicyModal.tsx
apps/web/module/Bookings/SingleView/components/modals/ModalHouseRules.tsx
apps/web/module/Bookings/SingleView/components/modals/ModalSafetyProperty.tsx

Added Things To Know modal
This is a task-story, to check and merge necessary changes and additions of files and codes specifically in Things To Know component.

[Task-Story] Added Things To Know modal

---

apps/web/common/components/BlackAsterisk.tsx

Added Black asterisk reusable component
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in booking item page ui.

[Task-Story] Added Black asterisk

---

apps/web/module/Bookings/SingleView/components/CheckoutProcess.tsx

Changed words
This is a task-story, to check and merge necessary changes and additions on files and codes specifically on booking item ui.

[Task-Story] Changed words

---

apps/web/module/Bookings/SingleView/components/WhereYouWillBe.tsx

Added read more on where youll be modal
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in where you'll be modal.

[Task-Story] Added read more on where youll be modal

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listing/index.ts
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/auth.ts
apps/api/src/routes/users/service/default.ts
apps/api/src/routes/users/service/personalInfo.ts
apps/web/module/AccountSettings/components/Address.tsx
apps/web/module/AccountSettings/hooks/useAddAddress.ts
apps/web/module/Bookings/SingleView/components/modals/ModalReporting.tsx
apps/web/module/Bookings/SingleView/components/modals/checkInOutCalendarModal.tsx
apps/web/module/Bookings/SingleView/index.tsx

Added get user profile api endpoint
To get data of user profile

[Task -Story] Added get user profile api endpoint

---

apps/web/module/hooks/useGetUserProfile.ts

Added custom hook for getting User Profile info
To connect to backend of getting user profile

[Task-Story] Added custom hook for getting User Profile info

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listing/service/listing.ts
apps/api/src/routes/listing/service/reservationListing.ts
apps/web/module/Bookings/SingleView/components/modals/ModalReporting.tsx
apps/web/module/Bookings/SingleView/components/modals/checkInOutCalendarModal.tsx
apps/web/module/Bookings/SingleView/index.tsx

…ndpoints
Adjusted table listing and reservation listing 
To correct table columns

[Task-Story] Adjusted listing and reservation listing database

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listing/service/listing.ts
apps/api/src/routes/listing/service/reservationListing.ts
apps/api/src/routes/listing/service/wishGroup.ts
apps/web/common/components/WishlistsItemContainer.tsx
apps/web/module/AccountSettings/BookingReviews.tsx
apps/web/module/AccountSettings/Wishlist.tsx
apps/web/module/AccountSettings/components/modals/AddWishlistModal.tsx
apps/web/module/Bookings/SingleView/components/ImageGallery.tsx
apps/web/module/Bookings/SingleView/components/SectionInfo.tsx
apps/web/module/Bookings/index.tsx

Modified listing table columns imageKeys
To make it a right term for images

[Tak - Story] Changed table columns imageKeys to images in Listing table

---

apps/web/module/Bookings/SingleView/components/ShareSave.tsx
apps/web/module/Bookings/SingleView/components/modals/SharePlaceModal.tsx

Created share modal and content
To make the button share work

[Task- Story] Created share modal and content

---

apps/web/common/store/useGuestAdd.ts
apps/web/module/Bookings/SingleView/components/modals/GuestAddModal.tsx

Added guest add modal.
For adding guests. It is a story.

[Task-Story] Create small modal with Guest add functionality

---

apps/web/module/AddReview/index.tsx

Changed final message and added listing name variable
For final message to be dynamic. It is a story.

[Task-Story] Change final message title for review listing

---

apps/web/module/Bookings/SingleView/components/WhereYouWillSleep.tsx

Added where you will sleep UI.
For setting up where you will sleep. It is a story.

[Task-Story] Where youll sleep UI

---

apps/web/module/AccountSettings/components/GovernmentId.tsx
apps/web/module/AccountSettings/components/modals/GovernmentIdModal.tsx

Added show list of ID on Government Id
This is a task-story, to check and merge necessary changes and additions on files and code specifically in personal info.

[Task-Story] Added show list of ID on Government Id

---

apps/web/common/components/SpecificMap.tsx
apps/web/module/Bookings/SingleView/components/Map.tsx
apps/web/module/Bookings/SingleView/components/WhereYouWillBeModal.tsx

Fixed where youll be map modal loading
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the booking item page ui.

[Task-Story] Fixed where youll be map modal loading

---

apps/api/package.json
apps/api/src/prisma/schema.prisma
apps/api/src/prisma/seed.ts
package.json

Added database seeder in prisma
To add 5 rows value in all tables
To Activate run "npm run seed"

[Task-Story] Added database seeder

---

apps/api/package.json
apps/api/src/common/service/api.ts
apps/api/src/routes/xendit/index.ts
apps/api/src/routes/xendit/services/default.ts
package-lock.json
package.json
packages/services/.eslintrc.js
packages/services/package.json
packages/services/src/config.ts
packages/services/src/encryption.ts
packages/services/src/index.ts
packages/services/tsconfig.json

Created a helper to encrypt object, array and string and decrypt
To easy access to function of encryption

[Task-Story] Created a helper to encrypt object, array and string and decrypt

---

apps/web/common/components/BookingBoxContainer.tsx
apps/web/common/components/Slider.tsx
apps/web/module/Bookings/index.tsx
apps/web/package.json
package-lock.json

Created sample implementation of image slider for listing box UI
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the booking item page ui.

[Task-Story] Created sample implementation of image slider for listing box UI

---

apps/web/common/components/ui/OvalTab.tsx
apps/web/module/Hosting/index.tsx

Created Hosting Page
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the lisitngs.

[Task-Story] Created Hosting Page

---

apps/web/module/HostProfile/components/HostReviews.tsx
apps/web/module/HostProfile/components/ReviewCard.tsx
apps/web/module/HostProfile/components/modals/AllReviewsModal.tsx
apps/web/module/HostProfile/types/AllReviewsModal.ts
apps/web/module/HostProfile/types/ReviewCard.ts

Added show all review modal.
To show all reviews. It is a story.

[Task-Story] Host profile show all reviews

---

apps/web/module/Hosting/ProgressPageTab.tsx

Created progress pages tab
This is a task-story, to check and merge necessary changes on files and codes specifically in the listings.

[Task-Story] Created progress pages tab

---

apps/web/module/Hosting/Reservation.tsx

Created Reservation Page
To view reservations. To check code and functionality. This is a story

[Task-Story] Created Reservation Page

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/payments/service/paymentMethod.ts
apps/web/module/AccountSettings/components/Payments.tsx
apps/web/module/AccountSettings/components/modals/AddCardDetailModal.tsx
apps/web/module/AccountSettings/hooks/useAddPaymentMethod.ts
packages/services/src/config.ts
packages/services/src/encryption.ts

Encrypt card information in frontend before saving
For card information security

[Task-Story] Encrypt card information in frontend before saving

---

apps/api/src/common/config/index.ts
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/auth.ts
apps/api/src/routes/users/service/default.ts
apps/web/module/Authentication/NewPassword/index.tsx
apps/web/module/Authentication/components/LoginForm.tsx
apps/web/module/Authentication/components/SignUpForm.tsx
apps/web/next.config.js
package-lock.json
packages/services/src/config.ts
packages/services/src/encryption.ts
turbo.json

encrypt password from frontend
For additional security

[Tak-Story] Encrypt password from the frontend

---

apps/api/src/prisma/schema.prisma
apps/api/src/prisma/seed/listingPrice.ts
apps/api/src/routes/listings/service/listing.ts

Updated listingPrice table and endpoints
To follow the correct logic

[Task-Story] Updated listingPrice table and endpoints

---

apps/api/src/prisma/schema.prisma
apps/api/src/prisma/seed/reportListing.ts
apps/api/src/routes/index.ts
apps/api/src/routes/listings/index.ts
apps/api/src/routes/reports/index.ts
apps/api/src/routes/reports/services/reportListing.ts
apps/web/common/store/useReportListingStore.ts
apps/web/module/Accommodation/components/modals/ReportListingModal.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/DefaultOption.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/Feedback.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/Inaccurate.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/Offensive.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/OffensiveTextArea.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/Reported.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/Scam.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/ScamSelectables.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/SomethingElse.tsx
apps/web/module/Bookings/SingleView/components/ReportListing/TextArea.tsx
packages/contract/src/ReportListing/zod.ts

Fixed report listing endpoint and backend
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the listings.

[Task-Story] Fixed report listing endpoint and backend

---

apps/api/package.json
apps/api/src/common/helpers/getListingPrice.ts
apps/api/src/prisma/schema.prisma
apps/api/src/prisma/seed/listingPrice.ts
apps/api/src/routes/bookings/services/default.ts
apps/api/src/routes/listings/service/listing.ts
package-lock.json

Calculate price on add booking for checking out
To get the correct value of total fee

[Task-Story] Calculated price on add booking for checking out

---

apps/api/src/routes/listings/index.ts
apps/api/src/routes/listings/service/jsons/reviews.ts
apps/api/src/routes/listings/service/reviews.ts
apps/web/common/helpers/governmentIdMap.ts
apps/web/module/AccountSettings/components/modals/GovernmentIdModal.tsx

Added Endpoints and Schema fo reviews by host id
To get group of datas of reviews by host Id

[Task-Story] Added Endpoints and Schema fo reviews by host id

---

apps/api/src/routes/bookings/services/default.ts
apps/api/src/routes/xendit/services/default.ts
apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/AccountSettings/components/modals/AddCardDetailModal.tsx
packages/contract/src/Booking/zod.ts
packages/contract/src/PaymentMethod/zod.ts

Removed cvv to encrypted card
To correct the logic needed

[Task-Story] Removed cvv on encrypted card

---

apps/api/src/routes/bookings/index.ts
apps/api/src/routes/bookings/services/default.ts

Added Bookings Page Endpoint
get all booking by userId and by hostId

[Task-Story] Added Bookings Page Endpoint

---

apps/web/common/constants/api-routes.ts
apps/web/module/Profile/hooks/useAddReportUser.ts
apps/web/module/Profile/hooks/useGetAllReportUsers.ts
apps/web/module/Profile/hooks/useGetReportUser.ts
apps/web/module/Profile/hooks/useGetReportUsersByReportedByUser.ts
apps/web/module/Profile/hooks/useGetReportUsersByReportedUser.ts

Added report users hooks
To communicate to backend api routes of report user

[Task-Story]  Added Report users hooks

---

apps/api/src/routes/users/service/personalInfo.ts
apps/web/common/helpers/governmentIdMap.ts
apps/web/module/AccountSettings/components/GovernmentId.tsx
apps/web/module/AccountSettings/components/modals/GovernmentIdModal.tsx

Added limit of 2 for uploading government id
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the improvements.

[Task-Story] Added limit of 2 for uploading government id

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/listings/index.ts
apps/api/src/routes/listings/service/jsons/notifications.ts
apps/api/src/routes/listings/service/notification.ts
apps/web/common/helpers/governmentIdMap.ts
apps/web/module/AccountSettings/components/modals/GovernmentIdModal.tsx

Added api endpoints for notifications
To get data of notifications by hostId

[Task-Story] Added api endpoint for notifications with mock data

---

apps/api/src/prisma/schema.prisma
apps/api/src/prisma/seed/user.ts
apps/api/src/routes/listings/service/listing.ts
apps/api/src/routes/payments/service/coupons.ts
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/beAHost.ts
apps/api/src/routes/users/service/hostDetails.ts
apps/web/common/helpers/governmentIdMap.ts
apps/web/module/AccountSettings/components/modals/GovernmentIdModal.tsx
apps/web/module/LandingPage/hooks/useChangeToHost.ts

Added a backend endpoint to add Host role to a User
To make a normal user as a host user

[Tas-Story] Added a backend endpoint to add Host role to a User

---

apps/web/module/LandingPage/components/ApplyToHostModal.tsx
apps/web/module/LandingPage/components/Header.tsx
apps/web/module/LandingPage/index.tsx

Added function to Apply to Host button in nav bar
To display a modal and make the user host after clicking the proceed button. This is a story.

[Task-Story] Added function to Apply to Host button in nav bar

---

apps/web/module/AccountSettings/Wishlist/WishlistsItemContainer.tsx

Not showing images in wish group page
To fix the issu found in wish group

[Task-Story] Image is not show on frontend fixed

---

apps/web/module/AccountSettings/Wishlist/SavedWishlists.tsx
apps/web/module/AccountSettings/Wishlist/WishlistsItemContainer.tsx

Some adjustments for wishlisted items.
For optimized code. It is a story.

[Task-Story] Use the WishlistBoxContainer on wishlist group page

---

apps/web/module/AccountSettings/components/modals/AddWishlistModal.tsx

Removed center alignment of wishgroup title and count in AddWishListModal
To meet the correct design

[Task-Story] Aligned wish group count and titile to left

---

apps/api/src/routes/listings/service/jsons/reviews.ts
apps/web/module/Host/Reviews/components/Reviews.tsx
apps/web/module/Host/hooks/useGetReviewsByHost.ts
apps/web/module/LandingPage/index.tsx

Added show all reviews for a Host
To display reviews and reply. To check code and functionality. It is a story.

[Task-Story] Show all reviews for a Host

---

apps/api/src/routes/index.ts
apps/api/src/routes/mock/bookings/default.ts
apps/api/src/routes/mock/bookings/index.ts
apps/web/module/AccountSettings/hooks/useGetToReviewById.ts
apps/web/module/AccountSettings/hooks/useGetToReviews.ts

Added endpoint for getting to reviews mock data
To add available datas in bookings to review

[Task-Story] Added a mock data for To Review

---

apps/api/src/routes/bookings/index.ts
apps/api/src/routes/bookings/services/earnings.ts

Added year to date summary to earning endpoints
To filled missing data

[Task-Story] Setup year-to-date summary mock endpoint

---

apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/default.ts
apps/api/src/routes/users/service/userProfile.ts
apps/web/module/Profile/Setup/index.tsx
apps/web/module/Profile/hooks/useGetProfile.ts
apps/web/module/Profile/hooks/useUpdateProfile.ts

update endpoint and hook for get profile and update profile
To make it mocked data

[Task-Story] Updated profile endpoint and hook

---

apps/web/common/components/Slider.tsx

Added show the next and back button when hover on item
This is  a task-story, to check and merge necessary changes and additions on files and codes specifically in the checkout improvements.

[Task-Story] Added show the next and back button when hover on item

---

apps/api/src/routes/listings/index.ts
apps/api/src/routes/listings/service/wishGroup.ts
apps/web/module/AccountSettings/Wishlist/WishlistsItemContainer.tsx
apps/web/module/AccountSettings/components/modals/AddWishlistModal.tsx
apps/web/module/AccountSettings/hooks/useRemoveFromWishGroup.ts
apps/web/module/Listing/components/BoxContainer.tsx

Fix issues in adding and removing wishlist.
Bug fix. It is a bug-fix.

[Task-Story] Fix issues in adding and removing wishlist

---

apps/api/src/routes/bookings/index.ts
apps/api/src/routes/bookings/services/paginatedBooking.ts.ts
apps/web/module/Bookings/hooks/useGetBookings.ts

Added paginated endpoint for booking
To minimize the response data

[Task-Story] Added paginated endpoint for getting user bookings

---

apps/api/src/routes/listings/index.ts
apps/api/src/routes/listings/service/jsons/listingsByHost.ts
apps/api/src/routes/listings/service/listingsByHost.ts
apps/web/module/Host/hooks/useGetListingsByHost.ts

Added endpoint and mock data for listings by host id
To have data for listings base from host

[Task-Story] Added mock data for listings by host

---

apps/api/src/routes/bookings/index.ts
apps/web/module/Host/Earnings/EarningsThisMonth.tsx
apps/web/module/Host/hooks/useGetThisMonthEarnings.ts
apps/web/module/LandingPage/index.tsx
apps/web/package.json
package-lock.json

Added Setup Earning this month UI
To view monthly earnings. To check code and functionality. It is a story.

[Task-Story] Setup Earning this month UI

---

apps/web/common/components/ui/StarRating.tsx
apps/web/module/AccountSettings/BookingReviews/BookingReviewItem.tsx
apps/web/module/AccountSettings/BookingReviews/index.tsx
apps/web/module/AddReview/index.tsx

Fixed issue on adding review
To submit reviews correctly

[Task-Story]  Investigated and fixed the error on Stars in review page

---

apps/web/common/types/global.ts
apps/web/module/AccountSettings/Wishlist/WishlistsItemContainer.tsx

Fixed bug on deleting single wishlist inside wishgroup
To remove error on deleting wish list

[Task-Story] Fixed bug  on deleting single wishlist inside wishgroup

---

apps/web/module/Listing/components/BoxContainer.tsx

Added next/link to each listing item
To redirect the user when the item is clicked. This is a story.

[Task-Story] Add next/link to each listing item

---

apps/api/src/routes/bookings/services/earnings.ts
apps/web/module/Bookings/index.tsx
apps/web/module/Host/Earnings/Paid.tsx
apps/web/module/Host/Earnings/components/Chart.tsx
apps/web/module/Host/hooks/useGetPaidEarnings.ts

Added setup Earning paid UI
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the earnings.

[Task-Story] Added setup Earning paid UI

---

apps/web/common/components/Table/HostTable.tsx

Added set up lists of added listing
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the listings.

[Task-Story]: Added set up lists of added listing

---

apps/api/src/common/middleware/auth/isUserLoggedIn.ts
apps/api/src/routes/users/index.ts
apps/api/src/routes/users/service/auth.ts
apps/api/src/routes/users/service/default.ts
apps/api/src/routes/users/service/userProfile.ts
apps/web/app/(profile)/profile/[userId]/page.tsx
apps/web/common/store/useSessionStore.ts
apps/web/module/Profile/Setup/FirstLevel/DecadeYouWereBornContent.tsx
apps/web/module/Profile/Setup/FirstLevel/FavoriteSongInHighSchoolContent.tsx
apps/web/module/Profile/Setup/FirstLevel/LanguagesISpeakContent.tsx
apps/web/module/Profile/Setup/FirstLevel/MyBiographyTitleContent.tsx
apps/web/module/Profile/Setup/FirstLevel/MyFunFactContent.tsx
apps/web/module/Profile/Setup/FirstLevel/MyMostUselessSkillContent.tsx
apps/web/module/Profile/Setup/FirstLevel/MyWorkContent.tsx
apps/web/module/Profile/Setup/FirstLevel/ObsessedWithContent.tsx
apps/web/module/Profile/Setup/FirstLevel/PetsContent.tsx
apps/web/module/Profile/Setup/FirstLevel/Section.tsx
apps/web/module/Profile/Setup/FirstLevel/SpendTooMuchTimeContent.tsx
apps/web/module/Profile/Setup/FirstLevel/WhereILiveContent.tsx
apps/web/module/Profile/Setup/FirstLevel/WhereIwentToSchoolContent.tsx
apps/web/module/Profile/Setup/index.tsx
apps/web/module/Profile/components/ConfirmedInformation.tsx
apps/web/module/Profile/components/HostListings.tsx
apps/web/module/Profile/components/HostReviews.tsx
apps/web/module/Profile/components/modals/AllReviewsModal.tsx
packages/contract/src/Session/zod.ts

Bug found in getting data and wrong process in inputs now fixed
To correct the process of user profile edit and view

[Task-Story] Bug Getting data of User Profile and in Edit Profile wrong process has been fixed

---

apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx
apps/web/module/Accommodation/store/useGuestsStore.ts

Added search query for checkout page for default value
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the checkout improvements.

[Task-Story] Added search query for checkout page for default value

---

apps/api/src/routes/api/payments/service/coupons.ts
apps/api/src/routes/api/payments/service/paymentMethod.ts
apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx

Adjusted backend response for paymnets related endpoint
To make the response to updated shapes

[Task-Story] Changed json response to reusable one in payments endpoints

---

apps/api/src/routes/assets/service/default.ts

Edited assests response to updated shapes
To make response into lattest shapes

[Task-Story] Changed json response to reusable one in assets endpoint

---

apps/api/src/common/helpers/validateCsrfToken.ts
apps/api/src/common/helpers/verifyCaptcha.ts
apps/api/src/common/middleware/auth/isOriginValid.ts
apps/api/src/common/middleware/auth/isUserLoggedIn.ts
apps/api/src/common/service/api.ts
apps/api/src/index.ts
apps/api/src/prisma/seed/user.ts
apps/api/src/routes/api/users/service/auth.ts
apps/api/src/routes/api/users/service/default.ts
apps/api/src/routes/api/xendit/services/default.ts
apps/web/module/AccountSettings/PersonalInfo/index.tsx
packages/constants/src/env-vars.ts
packages/constants/src/index.ts
packages/services/src/encryption.ts

Env added ro global packages
for easy maintainability

[Task-Story] Env added to global packages

---

apps/web/module/Accommodation/Checkout/PaymentOptions.tsx
apps/web/module/Accommodation/Checkout/PaymentSavedForm.tsx

Added CVV number before submitting pre defined payment method
For security. It is a story.

[Task-Story] Add CVV number before submitting pre defined payment method

---

apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx
apps/web/module/LandingPage/components/ApplyToHostModal.tsx
apps/web/module/LandingPage/components/Header.tsx

Added redirect to login if not login for Apply Host
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the improvements.

[Task-Story] Added redirect to login if not login for Apply Host

---

apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx
apps/web/module/AccountSettings/Wishlist/WorldMap.tsx

Automatic calculation of zoom and bounds base on fitBounds function from leaflet
For map render. It is a story.

[Task-Story] Automatic calculation of zoom and bounds base on fitBounds function from leaflet

---

apps/web/common/components/Table/PaymnetHistoryTable.tsx
apps/web/module/Host/PaymentHistory/BookingsTable.tsx
apps/web/module/Host/PaymentHistory/components/Status.tsx

Added table for Payment History
This is a task-story, to check and merge necessary changes on files and codes specifically in the earnings.

[Task-Story] Added table for Payment History

---

apps/api/src/routes/mock/bookings/index.ts
apps/api/src/routes/mock/bookings/services/jsons/earnings.ts
apps/api/src/routes/mock/bookings/services/paymentHistoryGraph.ts
apps/api/src/routes/mock/bookings/services/paymentHistoryTable.ts

Added payment history mock data api
To represents data of payment history graph and table

[Task-Story] Added Payment history mock data

---

apps/web/app/(host)/hosting/payment-history/graph/page.tsx
apps/web/app/(host)/hosting/payment-history/table/page.tsx
apps/web/module/Host/Listing/HostListingTable.tsx
apps/web/module/Host/PaymentHistory/BookingsTable.tsx
apps/web/module/Host/PaymentHistory/Graph.tsx
apps/web/module/Host/PaymentHistory/GraphTab.tsx
apps/web/module/Host/PaymentHistory/Table.tsx
apps/web/module/Host/PaymentHistory/TableTab.tsx
apps/web/module/Host/PaymentHistory/components/OverAllSummary.tsx
apps/web/module/Host/PaymentHistory/constants/tabs.tsx
apps/web/module/PaymentHistory/Graph.tsx

Combine graph and table to page
To view graph and table in tabs. This is a story.

[Task-Story] Combine graph and table to page

---

apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx
apps/web/module/Profile/components/ProfileCard.tsx

Profile card view modified depends on user role
For dynamic profile card view. It is a story.

[Task-Story] Change the content on user box on profile if the user is a guest

---

apps/web/common/store/useMarkerHover.ts
apps/web/common/store/useMarkerHoverStore.ts
apps/web/module/AccountSettings/Wishlist/SavedWishlists.tsx
apps/web/module/AccountSettings/Wishlist/WorldMap.tsx
apps/web/public/primary-marker.svg
apps/web/public/secondary-marker.svg

Marker color on hover effect
For wishlist items map effect. It is a story.

[Task-Story] Change marker color on Hover outside listing

---

apps/api/src/routes/mock/bookings/services/monthYearBooking.ts
apps/web/module/Host/PaymentHistory/hooks/useGetPaymentHistoryGraph.ts
apps/web/module/Host/PaymentHistory/hooks/useGetPaymentHistoryTable.ts

Add Hooks for payment history table and graph
Created hooks that will connect to mock API of payment history. This is a story.

[Task-Story] Add Hooks for payment history table and graph

---

apps/api/src/routes/mock/bookings/services/monthYear.ts
apps/api/src/routes/mock/bookings/services/monthYearBooking.ts
apps/web/module/Host/hooks/useGetMonthYearEarnings.ts
apps/web/module/Host/hooks/useGetMonthYearEarningsWithBookings.ts
apps/web/module/Host/hooks/useGetPaidEarnings.ts
apps/web/module/Host/hooks/useGetPaidEarningsWithBookings.ts
apps/web/module/Host/hooks/useGetThisMonthEarningsWithBookings.ts
apps/web/module/Host/hooks/useGetUpcomingEarningsWithBookings.ts
apps/web/module/LandingPage/index.tsx

Added custom hooks for bookings earnings
to get data of eranings  from backend

[Task-story]  Added custom hooks for bookings earnings

---

apps/api/src/routes/mock/bookings/services/thisMonth.ts
apps/web/module/Host/Earnings/EarningsPaid.tsx
apps/web/module/Host/Earnings/index.tsx

Fixed this month earnings issue
Corrected data needed

[Task-Story] Fixed this month earnings issue

---

apps/api/src/prisma/schema.prisma
apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx

Created Schema for Cart table
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the cart.

[Task-Story] Created Schema for Cart table

---

apps/api/src/routes/index.ts
apps/api/src/routes/mock/carts/default.ts
apps/api/src/routes/mock/carts/index.ts
apps/api/src/routes/mock/carts/jsons/carts.ts
apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx

Added mock endpoint for cart
To manipulate backend

[Task-Story] Created API Endpoints for Cart

---

apps/api/src/routes/mock/carts/default.ts
apps/web/module/Carts/hooks/useRemoveCartItem.ts

Adjusted Hook for delete Cart
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the cart.

[Task-Story] Adjusted Hook for delete Cart

---

apps/api/src/prisma/schema.prisma
apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/components/CheckoutBox.tsx

Added guest Schema
This is a task=story, to check and merge necessary changes and additions on files and codes specifically in the listing new schema.

[Task-Story] Added guest Schema

---

apps/api/src/prisma/schema.prisma

Created orisma schema fir bookable unit type
To add needed schema

feat(api): Created prisma schema for BookableUnitType

---

apps/api/src/prisma/schema.prisma

Added property Schema
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the listing new schema.

[Task-Story] Added property Schema

---

apps/api/src/prisma/schema.prisma

Added prisma schema for BookableUnit
Added needed schema

[Tak-Story] Added prisma schema for BookableUnit

---

apps/api/src/prisma/schema.prisma

Added reservation Schema
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the listing new shcema.

[Task-Story] Added reservation Schema

---

.eslintrc.js
apps/api/src/prisma/schema.prisma
apps/web/module/AccountSettings/PersonalInfo/index.tsx
packages/contract/src/PersonalInfo/zod.ts

Checked Front-end affected by Guest Schema and Fix if error exist
To check and fix the front-end affected by the Guest schema. This is a story.

[Task-Story] Checked Front-end affected by Guest Schema and Fix if error exist

---

apps/api/src/routes/mock/bookableUnitType/jsons/bookableUnitType.ts

Added BookableUnitType Json data
To make sure that data for bookableUnit is available

[Tak-Story] Added Jsons for BookableUnitType

---

apps/api/src/routes/mock/bookableUnit/jsons/bookableUnit.ts

Added BookableUnit JSON Shape
Created json shape for bookableUnit. This is a story.

[Task-Story] BookableUnit JSON Shape

---

apps/web/common/constants/api-routes.ts
apps/web/module/Host/BookableUnit/hooks/useAddBookableUnit.ts
apps/web/module/Host/BookableUnit/hooks/useGetBookableUnitByHostId.ts
apps/web/module/Host/BookableUnit/hooks/useGetByBookableUnitType.ts
apps/web/module/Host/BookableUnit/hooks/useGetOneBookableUnit.ts
apps/web/module/Host/BookableUnit/hooks/useUpdateBookableUnit.ts

Added Custom Hooks for BookableUnit
Created custom hooks for BookableUnit. To add, update, and get bookableUnit data from mock. This is a story.

[Task-Story] Hooks for BookableUnit

---

apps/web/module/Accommodation/Checkout/index.tsx
apps/web/module/Accommodation/Message.tsx
apps/web/module/AddReview/index.tsx
apps/web/module/Host/Earnings/EarningDetails.tsx
apps/web/module/Host/Reservation.tsx
apps/web/module/Profile/components/SwiperCustomButton.tsx

Added back button on earnings monthly page
To redirect the user to hosting/earnings when the back button has been clicked. This is a story.

[Task-Story] Add back button on earnings monthly page

---

apps/web/module/Listing/components/BoxContainer.tsx

Fixed heart icon bug issue.
For better UX. It is a bugfix.

[Task-Story] Fix heart icon bug in landing page

---

apps/api/src/common/middleware/auth/isUserLoggedIn.ts
apps/api/src/routes/api/listings/service/basicAboutPlace.ts
apps/api/src/routes/api/listings/service/cancellationPolicies.ts
apps/api/src/routes/api/listings/service/highLights.ts
apps/api/src/routes/api/listings/service/houseRules.ts
apps/api/src/routes/api/listings/service/listing.ts
apps/api/src/routes/api/listings/service/listingHighlights.ts
apps/api/src/routes/api/listings/service/listingPlaceOffers.ts
apps/api/src/routes/api/listings/service/placeOffers.ts
apps/api/src/routes/api/listings/service/reviews.ts
apps/api/src/routes/api/listings/service/rules.ts
apps/api/src/routes/api/listings/service/safetyProperty.ts
apps/api/src/routes/api/listings/service/wishGroup.ts
apps/api/src/routes/api/payments/service/coupons.ts
apps/api/src/routes/api/payments/service/paymentMethod.ts
apps/api/src/routes/api/reports/services/reportListing.ts
apps/api/src/routes/api/users/service/auth.ts
apps/api/src/routes/api/users/service/default.ts

Change all prisma function to reusable prisma
Optimize codes

[Task-Story] Updated all manual prisma to the reusable prisma function

---

apps/web/common/helpers/workspace.ts

Created reusable function for setting workspace
To check if user is current host or guest

[Task-Story] Setup localStore for account state

---

apps/web/module/Host/components/HeaderHost.tsx

Implemented locaStorage change on workspace change
To determine the user's selected item from the pop-over host or guest. This is a story.

[Task-Story] Implemented locaStorage change on workspace change

---

apps/web/common/components/HostSidebar.tsx

Created Hosting Sidebar
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the base layout.

[Task-Story] Created Hosting Sidebar

---

apps/api/src/common/service/file.ts

Add limit to each image upload to 10mb
Optimized image upload

[Tak-Story] Added limit to each image upload to 10mb

---

apps/web/module/Accommodation/components/ImageGallery.tsx
apps/web/module/Accommodation/components/WhereYouWillSleep.tsx
apps/web/module/Accommodation/components/modals/ImageGalleryModal.tsx
apps/web/module/AccountSettings/BookingReviews/BookingReviewItemPending.tsx
apps/web/module/AddReview/index.tsx
apps/web/module/Bookings/index.tsx
apps/web/module/Host/Earnings/EarningBookingsTable.tsx
apps/web/module/Host/Listing/HostListingTable.tsx
apps/web/module/Host/Reviews/components/Reviews.tsx
apps/web/module/Host/helpers/earningsColumns.tsx
apps/web/module/Profile/components/ListingCard.tsx
apps/web/module/Profile/components/ProfileCard.tsx
apps/web/module/Profile/components/ReviewCard.tsx
apps/web/module/Profile/components/modals/AllReviewsModal.tsx

Fixed layout error on next image
To fix the layout error on next/image. This is a story.

[Task-Story] Fix layout error on next image

---

apps/api/src/prisma/schema.prisma
apps/api/src/routes/mock/conversations/default.ts
apps/api/src/routes/mock/conversations/index.ts
apps/api/src/routes/mock/conversations/jsons/conversation.ts
packages/contract/src/Conversation/zod.ts

API Mock endpoints to get messages in conversation
To show message conversation

[Task-Story] Added  API Mock endpoints to get messages in conversation

---

apps/web/module/Host/Conversation/MessageConversation.tsx
apps/web/module/LandingPage/index.tsx

Added left and right message of guest and host like Messenger
To view host and guest conversation. This is a story.

[Task-Story] Add left and right message of guest and host like Messenger

---

apps/web/module/Host/Conversation/ChatSidebar.tsx

Created conversation sidebar
This is a task-story, to check and merge necessary changes and additions on files and codes specifically in the messaging.

[Task-Story] Created conversation sidebar
